version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
 
      - ./protected:/app/protected
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DB_ENGINE=django.db.backends.sqlite3
      - DB_NAME=db.sqlite3
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

