# Generated by Django 4.2.24 on 2025-09-11 18:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/assignmentpros/protected/task_files'), upload_to=''),
        ),
    ]
