# Generated by Django 4.2.24 on 2025-09-11 19:58

import assignments.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/assignmentpros/protected/task_files'), upload_to=assignments.models.task_file_upload_path, validators=[assignments.models.validate_file_extension, assignments.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/assignmentpros/protected/task_files'), upload_to=assignments.models.task_file_upload_path, validators=[assignments.models.validate_file_extension, assignments.models.validate_file_size]),
        ),
    ]
