# Generated by Django 4.2.21 on 2025-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_task_amount_taskpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
